[package]
name = "generate_target_configs"
version = "0.1.0"
edition = "2024"

[dependencies]
benchmark = { path = "../../benchmarks/benchmark" }
tidehunter = { path = "../../tidehunter" }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
anyhow = "1"


