---
testbed_id: "${USER}-tidehunter"
cloud_provider: aws
token_file: "/Users/${USER}/.aws/credentials"
ssh_private_key_file: "/Users/${USER}/.ssh/id_rsa"
regions:
  - us-east-1
specs: i8g.4xlarge
repository:
  url: https://@github.com/mystenlabs/tidehunter.git
  commit: main
target_configs_path: "./orchestrator/assets/target_configs.yml"
