- db_parameters:
      frag_size: 134217728
      max_maps: 16
      max_dirty_keys: 32
      snapshot_written_bytes: 134217728
      snapshot_unload_threshold: 268435456
      unload_jitter_pct: 10
      direct_io: false
  stress_client_parameters:
      mixed_threads: 1
      write_threads: 1
      write_size: 1024
      key_len: 32
      writes: 20000000
      operations: 20000000
      background_writes: 0
      no_snapshot: false
      report: true
      key_layout: Uniform
      tldr: ""
      preserve: false
      read_mode: Get
      backend: Tidehunter

- db_parameters:
      frag_size: 134217728
      max_maps: 16
      max_dirty_keys: 32
      snapshot_written_bytes: 134217728
      snapshot_unload_threshold: 268435456
      unload_jitter_pct: 10
      direct_io: false
  stress_client_parameters:
      mixed_threads: 1
      write_threads: 1
      write_size: 1048576
      key_len: 32
      writes: 50000
      operations: 50000
      background_writes: 0
      no_snapshot: false
      report: true
      key_layout: Uniform
      tldr: ""
      preserve: false
      read_mode: Get
      backend: Tidehunter

- db_parameters:
      frag_size: 134217728
      max_maps: 16
      max_dirty_keys: 32
      snapshot_written_bytes: 134217728
      snapshot_unload_threshold: 268435456
      unload_jitter_pct: 10
      direct_io: false
  stress_client_parameters:
      mixed_threads: 10
      write_threads: 10
      write_size: 10240
      key_len: 32
      writes: 20000000
      operations: 20000000
      background_writes: 0
      no_snapshot: false
      report: true
      key_layout: Uniform
      tldr: ""
      preserve: false
      read_mode: Get
      backend: Tidehunter
      path: "/home/ubuntu/working_dir"
