- db_parameters:
      frag_size: 134217728
      max_maps: 16
      max_dirty_keys: 32
      snapshot_written_bytes: 134217728
      snapshot_unload_threshold: 268435456
      unload_jitter_pct: 10
      direct_io: false
  stress_client_parameters:
      mixed_threads: 16
      write_threads: 16
      write_size: 512
      key_len: 32
      writes: 10000000
      operations: 300000
      background_writes: 0
      no_snapshot: false
      report: true
      key_layout: Uniform
      tldr: ""
      preserve: false
      read_mode: Get
      backend: Tidehunter
      path: "/home/ubuntu/working_dir"
      read_percentage: 100

- db_parameters:
      frag_size: 134217728
      max_maps: 16
      max_dirty_keys: 32
      snapshot_written_bytes: 134217728
      snapshot_unload_threshold: 268435456
      unload_jitter_pct: 10
      direct_io: false
  stress_client_parameters:
      mixed_threads: 16
      write_threads: 16
      write_size: 512
      key_len: 32
      writes: 10000000
      operations: 300000
      background_writes: 0
      no_snapshot: false
      report: true
      key_layout: Uniform
      tldr: ""
      preserve: false
      read_mode: Get
      backend: Rocksdb
      path: "/home/ubuntu/working_dir"
      read_percentage: 100
